name: release
on:
  push:
    branches:
      - "main"
jobs:
  test:
    uses: devtemplates/github/.github/workflows/call_test.yml@test-v1
  release:
    needs: [test]
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    uses: ./.github/workflows/call_release.yml
