name: release
on:
  push:
    branches:
      - "main"
jobs:
  test:
    uses: devtemplates/github/.github/workflows/call_test.yml@test-v1
  release-please:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
      - name: Use Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v3
      - name: Install
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci
      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
