name: release
on:
  push:
    branches:
      - "main"
      - "next"
jobs:
  test:
    uses: ./.github/workflows/call_test.yml
  release:
    needs: [test]
    uses: ./.github/workflows/call_release.yml
